---
- name: Install Router
  hosts: midtier
  tasks:    
  - name: Install Router if not exists
    unarchive: 
      src: ~/Router.tgz 
      dest: ~/
  - name: Set Up Docker Curl
    command: ~/Router/scripts/set-up-docker.sh
  - name: Make Space to Commit Image
    command: ~/Router/scripts/change-storage-location-docker.sh

- name: Execute Router Container 
  hosts:
  - midtier
  #- bucket
  #- client
  tags: compose_up_router
  tasks:
    - name: Change to docker group 
      command: sudo newgrp docker
    
    - name: Compose Up Router
      command: ~/Router/scripts/docker-compose-up.sh
